#!/bin/bash
yum -y install php
yum -y install php-mbstring
yum -y install php-intl
yum -y install httpd

# add this later
# curl -s https://getcomposer.org/installer | php
# mv composer.phar ~/.local/bin/composer
