#!/bin/bash
yum -y install php8.1
yum -y install php-mbstring
yum -y install php-intl
yum -y install libapache2-mod-php8.1

# add this later
# curl -s https://getcomposer.org/installer | php
# mv composer.phar ~/.local/bin/composer
